### ISSUE TITLE
Vasyl HALLLLP

### ISSUE THREAD

**Issue by kolybasov** [kolybasov/bundlers-comparison#1]
@berezovyy could you write something there?

**Comment by berezovyy** [comment]
NOPE

**Comment by berezovyy** [comment]
<img width="213" alt="Screenshot at May 03 14-48-41" src="https://user-images.githubusercontent.com/3331480/67844954-4b689a00-fb07-11e9-957f-b46ef3e6e85b.png">

**Comment by kolybasov** [comment]
Sorry, testing an emails


On 30 October 2019 at 11:20:05, Vasyl Berezovyy (notifications@github.com) wrote:

NOPE

**Comment by berezovyy** [comment]
Haaalp

**Comment by berezovyy** [comment]
123123123123213

**Comment by kolybasov** [comment]
What


On 31 October 2019 at 14:05:31, Vasyl Berezovyy (notifications@github.com) wrote:

123123123123213

**Comment by kolybasov** [comment]
If 


On 31 October 2019 at 14:05:31, Vasyl Berezovyy (notifications@github.com) wrote:

123123123123213

**Comment by kolybasov** [comment]
I


On 31 October 2019 at 14:05:31, Vasyl Berezovyy (notifications@github.com) wrote:

123123123123213

**Comment by kolybasov** [comment]
Want to send many messages


On 31 October 2019 at 14:05:31, Vasyl Berezovyy (notifications@github.com) wrote:

123123123123213
